# Generated by Django 5.2 on 2025-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketmodel',
            name='location',
            field=models.TextField(),
        ),
    ]
