# Generated by Django 5.2 on 2025-04-25 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_marketmodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketmodel',
            name='logo',
        ),
    ]
