# Generated by Django 5.2 on 2025-04-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_marketmodel_logo'),
        ('product', '0002_remove_productmodel_picture'),
        ('rate', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='market.marketmodel'),
        ),
        migrations.AlterField(
            model_name='ratemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='product.productmodel'),
        ),
    ]
