# Generated by Django 5.2 on 2025-04-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_alter_ratemodel_market_alter_ratemodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='rate',
            field=models.FloatField(),
        ),
    ]
