# Generated by Django 5.2 on 2025-05-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.PositiveIntegerField(default=8418),
        ),
    ]
